# Generated by Django 4.2 on 2025-06-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_riskprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='auto_rebalance_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
