# Generated by Django 5.2.3 on 2025-06-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
